packages:
  - apps/*
  - packages/*
  - packages/infrastructure/*
  - packages/execution/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver
